### ISSUE TITLE
Hard turn limit for collimat?

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#224]
There seems to be a hard turn limit of 10k turns for collimation, as particle loss arrays are typically written as ` part_abs(j) = 10000*ie + iturn` where `ie` is the element number. This seems to be an encoding of where and when a particle was lost.

If this is correct, the COLL block should check that the user isn't trying to run for an invalid amount of turns, and if that case stop and refuse to run, since the output will be confused.

**Comment by kyrsjo** [comment]
Paging @rbruce1 @amereghe @JamesMolson ; this would be a blocker for @Pingul ; we should either avoid this (use two arrays?) OR at least raise the limit AND ANYWAY warn the user if the limit is exceeded...

**Comment by kyrsjo** [comment]
Oh, and there is also the fun with `ipart(j)+100*samplenumber` that is all over the code, where samplenumber goes from 1 to `nloop`; this would be broken for `hugenpart` if `nloop.gt.1`. I should probably put a check for that...

Also, this means that the particle indices in DUMP and collimation output files are NOT matching, as DUMP uses the following: `nlostp(j)+(samplenumber-1)*npart`. I propose to change collimation to put it in line with DUMP's more logical convention...

**Comment by kyrsjo** [comment]
Oh, and there is this gold nugget:
```
      if (cern) then
!
        open(unit=41,file='stuff')
        write(41,*) samplenumber
        close(41)
        open(unit=41,file='stuff')
        read(41,*) smpl
        close(41)
!GRD
        pfile(1:8) = 'tracks2.'
        if(samplenumber.le.9) then
           pfile(9:9) = smpl
           pfile(10:13) = '.dat'
        elseif(samplenumber.gt.9.and.samplenumber.le.99) then
           pfile(9:10) = smpl
           pfile(11:14) = '.dat'
        elseif(samplenumber.gt.99.and.                                  &
     &samplenumber.le.int(mynp/napx00)) then
           pfile(9:11) = smpl
           pfile(12:15) = '.dat'
        endif
!GRD
        if(samplenumber.le.9)                                           &
     &open(unit=38,file=pfile(1:13))
        if(samplenumber.gt.9.and.samplenumber.le.99)                    &
     &open(unit=38,file=pfile(1:14))
        if(samplenumber.gt.99.and.                                      &
     &samplenumber.le.int(mynp/napx00))                                 &
     &open(unit=38,file=pfile(1:15))
!GRD
        else
!
        open(unit=38,file='tracks2.dat')
!
        endif
```

**Comment by JamesMolson** [comment]
I think only @GuillaumeRD can answer that last part

**Comment by kyrsjo** [comment]
Regarding `part_abs`: It seems that it is only used to check if a particle has been absorbed (when it is > 0); it is actually never written out (except in a commented out code 'INFOijk'.

Also, we found this:
```
                iturn_last_hit = part_hit_before(j)-                    &
     &int(part_hit_before(j)/10000)*10000
```
And then there is part_hit(), which is set in collimate2 etc., where it is called `lhit` as:
```
            lhit(j) = 10000*ie + iturn
```
This is used for logic like this: `if ( part_hit(j).eq.(10000*ie+iturn) ) then` which is found all over the code to output etc.; this is probably a much larger problem than the original one (part_abs, which is just used as a flag).

**Comment by GuillaumeRD** [comment]
I am indeed the original coder of `part_abs`: at the time, collimation tracking studies were not expected to exceed 1k turns, and I needed an identifier for where and when a particle would get lost.

As for the other "gold nuggets", those were quick-and-dirty solutions implemented to get over the 64 particles limit; obviously since then tracking needs have changed and the source code got vastly improved on. All the existing tags and identifiers a la `part_abs` can (and should) be replaced to better fit with the current technology.

**Comment by GuillaumeRD** [comment]
ah, no worries at all! IIRC, I implemented the `cern` flag to better manage LHC simulations compared to RHIC ones, which generated smaller `track2.dat` files. I believe this flag can now be deleted.

**Comment by kyrsjo** [comment]
A more worrying thing: With hugenblz, `ie` tops out at 400'000. The expression
```10000*ie + iturn```
can then give results up to 4'000'009'999=1.86*2^31. This means that if this value is stored in a 32-bit signed integer, it will overflow!

Demonstration:
```
      program testint

      integer testvar

      testvar = 2147483647    ! 2^31-1
      write (*,*) testvar
      
      testvar = testvar+1
      write (*,*) testvar

      end program testint
```
Output:
```
$ gfortran check.f -o check 
$ ./check 
  2147483647
 -2147483648
```

Now, as long as we are just comparing negative part_hit to the negative result of the expression, things *should* work, but ehh.. @JamesMolson , you probably fix this in your branch for use with FCC.

**Comment by kyrsjo** [comment]
I made a patch to check the number of turns and merged it, see #273 . Integer overflow and other problems are still there.

**Comment by kyrsjo** [comment]
This issue also affects @jfwagner , who is running the collimation version > 10k turns.

From his presentation @Pingul had the same problem https://indico.cern.ch/event/656428/contributions/2674331/attachments/1501289/2338222/CWG2.pdf

**Comment by Pingul** [comment]
Joschka also asked what output files got corrupted after 10k turns. I answered that the only one I was aware of is `coll_summary.dat`, but more could potentially be broken. Are there more files that are problematic @kyrsjo?

**Comment by kyrsjo** [comment]
Thanks @Pingul , I don't know, but coll_summary is normally pretty important...

@JamesMolson , would you be interested in fixing it? I think it's either you and me, and it affects FCC...

Battleplan:
1. Rename affected array from `part_abs` to `part_abs_turn`
2. Add new array `part_abs_pos`
3. Change how part_abs is used.
4. Fix anything that no longer compiles because we changed the array name.
5. Commit and repeat for the next array

**Comment by Pingul** [comment]
@kyrsjo: I was talking to @jfwagner, and we looked into the coll_summary file a little. From what I gather it does not seem to use `part_abs` as we initially thought:

```       open(unit=50, file='coll_summary.dat')
      write(50,*)                                                       &
     &'# 1=icoll 2=collname 3=nimp 4=nabs 5=imp_av 6=imp_sig 7=length'
      do icoll = 1, db_ncoll
        if(db_length(icoll).gt.0d0) then
        write(50,'(i4,1x,a,2(1x,i5),2(1x,e15.7),3x,f3.1)')              &
     &icoll, db_name1(icoll),cn_impact(icoll), cn_absorbed(icoll),      &
!                                           ^ note ^
```

Tracing `cn_impact` backwards shows the following:

```
! Line 28205, inside the collimation routine
          do j=1,max_ncoll
            cn_impact(j) = 0
            cn_absorbed(j) = 0
            ...
          enddo
```
! Line 30062, still in the collimation routine
              cn_impact(icoll) = cn_impact(icoll) + 1
```

My guess is almost that statistics for the coll_summary file is being recorded separately, and that `part_abs` is not used.

**Comment by kyrsjo** [comment]
Fixed in #318
